# Generated by Django 4.0.3 on 2022-03-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('assest_id', models.AutoField(primary_key=True, serialize=False)),
                ('assest_desc', models.CharField(max_length=100)),
                ('assest_loc', models.CharField(choices=[('Level-1', 'Level-1'), ('Level-2', 'Level-2'), ('Level-3', 'Level-3'), ('Level-4', 'Level-4')], max_length=100)),
                ('assest_tag', models.CharField(max_length=100)),
                ('assest_group', models.CharField(max_length=100)),
                ('asset_name', models.CharField(max_length=100)),
                ('asset_category', models.CharField(choices=[('Electronics', 'Electronics'), ('Electrical', 'Electrical'), ('Civil', 'Civil'), ('Mechanical', 'Mechanical'), ('Spare', 'Spare'), ('Other', 'Other')], max_length=100)),
                ('asset_serial_No', models.CharField(max_length=100)),
                ('asset_manufacturer', models.CharField(max_length=100)),
                ('date_purchased', models.DateTimeField()),
                ('date_warranty', models.DateTimeField()),
                ('asset_warranty', models.BooleanField(default=False)),
                ('asset_active', models.BooleanField(default=False)),
                ('asset_Maintainable', models.BooleanField(default=False)),
                ('assest_main_date', models.DateField()),
            ],
        ),
    ]
