# Generated by Django 4.0.3 on 2022-03-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_asset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='assest_desc',
            new_name='asset_desc',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='assest_group',
            new_name='asset_group',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='assest_id',
            new_name='asset_id',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='assest_loc',
            new_name='asset_loc',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='assest_main_date',
            new_name='asset_main_date',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='assest_tag',
            new_name='asset_tag',
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_category',
            field=models.CharField(choices=[('Electrical', 'Electrical'), ('Civil', 'Civil'), ('Mechanical', 'Mechanical'), ('Spare', 'Spare'), ('Other', 'Other')], max_length=100),
        ),
    ]
