# Generated by Django 2.1.15 on 2022-03-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_assest_desc_asset_asset_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=100)),
                ('asset_name', models.CharField(max_length=100)),
                ('asset_tag', models.CharField(max_length=100)),
                ('asset_serial_No', models.CharField(max_length=100)),
                ('asset_loc', models.CharField(max_length=100)),
                ('date_main', models.DateTimeField()),
                ('asset_desc', models.CharField(max_length=100, null=True)),
                ('asset_assign', models.CharField(max_length=100, null=True)),
                ('date_solved', models.DateTimeField(null=True)),
                ('asset_comments', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
