# Generated by Django 2.1.15 on 2022-03-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_assetmain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmain',
            name='asset_assign',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assetmain',
            name='asset_comments',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assetmain',
            name='asset_desc',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assetmain',
            name='date_solved',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
