# Generated by Django 2.1.15 on 2022-03-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20220314_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmain',
            name='asset_status',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
