# Generated by Django 2.1.15 on 2022-03-15 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_assetmain_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmain',
            name='date_main',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
